#!/usr/bin/env bash


echo "// Autogenerated by scripts/generate-commands.sh"
echo

commands=""
for path in `find src/commands/autoload -name "*.ts" ! -name "index.ts"`; do
  pathName=$(basename $path .ts)
  moduleName=$(echo $pathName | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g' | sed 's/ //g')
  echo "import $moduleName from './$pathName';"
  commands="$commands$moduleName, "
done

echo
echo "export default [$commands];"
